import React, { useEffect } from 'react';
import { t } from 'i18next';
import { useNavigate } from 'react-router';
import Typography from '../../components/Typography';
import { Container, FAQ, FAQBody, Headings, ListItem, ListItems, Section, Wrapper } from './styled';

const FAQPage = () => {
	useEffect(() => {
		document.title = 'EnergyClue | FAQs';
	}, []);
	let navigate = useNavigate();
	function gotoQuotes() {
		navigate('/get-quotes');
	}
	return (
		<Wrapper>
			<Container>
				<Headings>
					<Typography
						variant="h1"
						color="black"
						align="center"
					>
						{t('FAQPAGE.HEADING')}
					</Typography>
					<Typography
						variant="body"
						color="black"
						align="center"
						className="sub-heading"
					>
                    “&nbsp;Go Green with EnergyClue Solar Power - The Cost-Effective Option of Fueling Your Home With Sunlight!&nbsp;“
					</Typography>
				</Headings>
				<Section>
					<Typography
						variant="h3"
						color="black"
						align="left"
						className="faq-heading"
					>
                        General Faq :
					</Typography>
					<FAQBody>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                1. What is a Solar PV System and how does it work?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                A solar photovoltaic system, also known as a PV system, is a large group of solar panels that collect
                                sunlight and turn it into electricity. The electricity generated by the PV system can be used to power
                                homes and businesses.
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                They are made up of photovoltaic cells that generate an electric current when they are hit by sunlight.
                                The cells are connected together in a series to form a panel with many cells.
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                The inverter takes the electricity generated by the solar panel and converts it to alternating current (AC)
                                which is usable in homes or businesses by changing its voltage from direct current (DC).
							</Typography>
						</FAQ>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                2. What factors are important to consider when planning to go solar?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                If you planning to install a solar plant, below are some things to consider:
							</Typography>
							<ListItems>
								<ListItem>Finding out how much money you can save on your electricity bill every year</ListItem>
								<ListItem>What is the availability of shadow-free area on your rooftop or building premises?</ListItem>
							</ListItems>
						</FAQ>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                3. How much is the average life of the solar panels?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                The life of a solar panel is determined by a number of factors. The most important ones are the climate,
                                the quality and type of panels, and the way they are installed.
                                The average life of solar panels is 25 years. However, this may vary depending on the factors
                                mentioned above.
							</Typography>
						</FAQ>
					</FAQBody>
				</Section>
				<Section>
					<Typography
						variant="h3"
						color="black"
						align="left"
						className="faq-heading"
					>
                        Finance :
					</Typography>
					<FAQBody>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                1. How much does a Solar PV system cost?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                Solar PV systems are becoming a more and more attractive energy solution worldwide due to the
                                declining costs of solar panels and installation.
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                So how much does a Solar PV system cost? Well, it depends on your location, the size of your roof,
                                what type of system you want (residential or commercial), the amount of energy you want generated.
							</Typography>
						</FAQ>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                2. Is Solar Power cheaper than the grid and diesel power?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                Solar power is cheaper than the grid and diesel power. Solar power is a renewable and clean source of
                                energy. It doesn&#39;t emit any harmful gases into the environment. On the other hand, diesel generators are
                                expensive and polluting.
							</Typography>
						</FAQ>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                3. How will I save from Rooftop Solar plant?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                A rooftop solar plant is a good idea for people who want to save money on their electricity bills. The
                                cost of installation and the electricity generated by the solar panels will depend on a number of factors.
                                There are many factors that affect the cost of installing a rooftop solar plant, such as size, location, and
                                type of system.
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                The size of your solar panel will also have an impact on how much you save from your monthly
                                electricity bill. A 2kW system will provide around 2000 kWh per year, so it would take 10 years before
                                you would break even on the installation costs.
							</Typography>
						</FAQ>
					</FAQBody>
				</Section>
				<Section>
					<Typography
						variant="h3"
						color="black"
						align="left"
						className="faq-heading"
					>
                        Installation &amp; Maintainence :
					</Typography>
					<FAQBody>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                1. How much time does it take to install a Solar PV system?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                Installing a solar PV system is a complex process that can take anywhere from one day to a few
                                weeks, depending on the size of the project and the complexity of installation.
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                Some things that can affect installation time are:
							</Typography>
							<ListItems>
								<ListItem className='list-dash'>The size of the project (a large solar PV system will take more time to install than a smaller one)</ListItem>
								<ListItem className='list-dash'>The level of complexity (a system with many wiring connections will take more time to install than
                                    one with fewer connections).</ListItem>
								<ListItem className='list-dash'>The type of roofing material (roofs with different types of material may require special design
                                    considerations).</ListItem>
								<ListItem className='list-dash'>Whether or not there is an existing electrical panel (if there is already an electrical panel on the roof,
                                    this may reduce installation time).</ListItem>
							</ListItems>
						</FAQ>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                2. The roofs of my premises are weak. Can I put Solar PV on my roof?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                EnergyClue will conduct a thorough evaluation to determine whether a solar plant can be installed on
                                your property.
							</Typography>
						</FAQ>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                3. What would be the annual maintenance cost involved for a solar PV system?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                The annual maintenance cost for a solar PV system can vary depending on factors like the size of the
                                system, the type of inverter used, and the frequency of inspections.
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                For example, if you have a 1 kW solar PV system and an inverter that is rated at 10 years, then you
                                would need to spend $1.00 per year on maintenance costs.
							</Typography>
						</FAQ>
					</FAQBody>
				</Section>
				<Section>
					<Typography
						variant="h3"
						color="black"
						align="left"
						className="faq-heading"
					>
                    EnergyClue Specific FAQ :
					</Typography>
					<FAQBody>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                1. Why should I choose EnergyClue over other Solar Developers?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                Listed below are core strengths of EnergyClue. This makes EnergyClue stand out among its
                                counterpart:
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
								display="block"
							>
								<span className='bold'>Solar expertise:&nbsp;</span>EnergyClue is run by power industry experts. We are one of the few companies with
                                complete in-house capabilities in all areas, including design, engineering, mono solar panels, pv solar
                                panels, solar pumps, monitoring, and maintenance.
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
								display="block"
							>
								<span className='bold'>World class organization:&nbsp;</span>We follow global best practices across Products, Process, Technology and
                                Safety.
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
								display="block"
							>
								<span className='bold'>Agility and responsiveness:&nbsp;</span>EnergyClue ensures that the Customer is at the heart of the organisation
                                with our quick turnaround times - from capacity analysis, commercial proposal, site-specific
                                customization, and so on - to our quick, committed-timeline implementation. Our high repeat rates
                                attest to our focus on customer service.
							</Typography>
						</FAQ>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                2. Why do we connect with vendors through EnergyClue, when they are also connecting us to local
                                vendors?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                Since you won&#39;t need to look up the background of the suppliers, we at Energy Clue always strive to
                                offer you only the greatest and highest-quality vendors. Furthermore, we will give you many quotes
                                after just one site visit, saving you the time and effort of calling other vendors. Save money and time.
                                (This is only an example; please create a catchy slogan similar to this.)
							</Typography>
						</FAQ>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                3. Does EnergyClue help with getting permits for installing the plant?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                EnergyClue at its own cost takes the complete responsibility of taking all the necessary regulatory
                                approvals and permits required for the operation of the solar plant.
							</Typography>
						</FAQ>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                3. What is the benefit of referring services to friends or family?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
							>
                                Are you ready to win Thank You Gifts. Just by referring your mobile number as referral code to your
                                friends and family member. Visit Energy clue
							</Typography>
						</FAQ>
					</FAQBody>
				</Section>
				<Section>
					<Typography
						variant="h3"
						color="black"
						align="left"
						className="faq-heading"
					>
                        Contact Info :
					</Typography>
					<FAQBody>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                1. How do I get a quote from EnergyClue?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
								display="block"
							>
                                You can write a mail to EnergyClue or you could fill the form. click here&nbsp; <button className='inline-button' onClick={gotoQuotes}>Get Quote</button>&nbsp;and fill form
							</Typography>
						</FAQ>
						<FAQ>
							<Typography
								variant="h5"
								color="black"
								align="left"
								className="que"
							>
                                2. How do I get in touch with someone from EnergyClue in case of further doubts?
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
								display="block"
							>
								<span className='bold'>Email:&nbsp;</span><a className='link-text' href="mailto:energyclue123@gmail.com">energyclue123@gmail.com</a>
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
								display="block"
							>
								<span className='bold'>Sales support:&nbsp;</span><a className='link-text' href="tel:6359798991">+91 635 97 98 99 1</a>
							</Typography>
							<Typography
								variant="body"
								color="black"
								align="left"
								weight="400"
								className="ans"
								display="block"
							>
								<span className='bold'>Whatsapp Chat support:&nbsp;</span><a className='link-text' href="https://api.whatsapp.com/send?phone=916359798991">+91 635 97 98 99 1</a>
							</Typography>
						</FAQ>
					</FAQBody>
				</Section>
			</Container>
		</Wrapper>
	);
};

export default FAQPage;